
name: Jekyll Boilerplate
title: The Jekyll Boilerplate
tagline: This is a short description of the site.
description: This is the longer version of the site description. It will be placed in the head of the document.
url: https://devhtml.dmurphyweb.com

# Contact Form
cognito-form-key: W2wJKdnZb0eaNWDs1Qh_hQ
cognito-data-form: 9

# Collections

collections_dir: collections

collections:
  sample_collection:
    # output: true -> use this option if you would like the collection outputed to static html pages.

permalink: /blog/:title/

destination: public

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


# Exculde these files and folders
exclude: [
  "gulpfile.js",
  "package-lock.json",
  "package.json",
  "README.md",
  "_scripts",
  "scripts",
  "index.js",
  "sass",
  "src",
  "webpack",
  "webpack.config.js",
]